apiVersion: v1
kind: Secret
metadata:
  name: $APP_INSTANCE_NAME-grafana
  labels:
    app.kubernetes.io/name: $APP_INSTANCE_NAME
type: Opaque
data:
  admin-user: YWRtaW4=
  admin-password: R2FNcmMxVmtTZA==
