properties:
  APP_INSTANCE_NAME:
    type: string
    x-google-marketplace:
      type: NAME
  NAMESPACE:
    type: string
    x-google-marketplace:
      type: NAMESPACE

  IMAGE_ALERTMANAGER:
    type: string
    default: $REGISTRY/prometheus/alertmanager:$TAG
    x-google-marketplace:
      type: IMAGE
  IMAGE_KUBE_STATE_METRICS:
    type: string
    default: $REGISTRY/prometheus/kubestatemetrics:$TAG
    x-google-marketplace:
      type: IMAGE
  IMAGE_NODE_EXPORTER:
    type: string
    default: $REGISTRY/prometheus/nodeexporter:$TAG
    x-google-marketplace:
      type: IMAGE
  IMAGE_PROMETHEUS:
    type: string
    default: $REGISTRY/prometheus/server:$TAG
    x-google-marketplace:
      type: IMAGE
  IMAGE_PUSHGATEWAY:
    type: string
    default: $REGISTRY/prometheus/pushgateway:$TAG
    x-google-marketplace:
      type: IMAGE
  IMAGE_GRAFANA:
    type: string
    default: $REGISTRY/prometheus/grafana:$TAG
    x-google-marketplace:
      type: IMAGE
  IMAGE_PROMETHEUS_INIT:
    type: string
    default: $REGISTRY/prometheus/debian9:$TAG
    x-google-marketplace:
      type: IMAGE

  #TODO(khajduczenia): reduce the permissions
  ALERTMANAGER_SA:
    type: string
    x-google-marketplace:
      type: SERVICE_ACCOUNT
  GRAFANA_SA:
    type: string
    x-google-marketplace:
      type: SERVICE_ACCOUNT
  NODE_EXPORTER_SA:
    type: string
    x-google-marketplace:
      type: SERVICE_ACCOUNT
  KUBE_STATE_METRICS_SA:
    type: string
    x-google-marketplace:
      type: SERVICE_ACCOUNT
      serviceAccount:
        roles:
        - type: ClusterRole
          rulesType: PREDEFINED
          rulesFromRoleName: cluster-admin
  PROMETHEUS_SA:
    type: string
    x-google-marketplace:
      type: SERVICE_ACCOUNT
      serviceAccount:
        roles:
        - type: ClusterRole
          rulesType: PREDEFINED
          rulesFromRoleName: cluster-admin

required:
- APP_INSTANCE_NAME
- NAMESPACE
- IMAGE_ALERTMANAGER
- IMAGE_KUBE_STATE_METRICS
- IMAGE_NODE_EXPORTER
- IMAGE_PROMETHEUS
- IMAGE_PUSHGATEWAY
- IMAGE_GRAFANA
- IMAGE_PROMETHEUS_INIT
