application_api_version: v1beta1
properties:
  name:
    type: string
    x-google-marketplace:
      type: NAME
  namespace:
    type: string
    x-google-marketplace:
      type: NAMESPACE
  prometheus.replicas:
    type: integer
    title: Prometheus replicas
    description: The number of replicas for Prometheus StatefulSet
    default: 2
    minimum: 1
  grafana.password:
    type: string
    x-google-marketplace:
      type: GENERATED_PASSWORD
      generatedPassword:
        length: 12
  prometheus.image:
    type: string
    default: $REGISTRY:$TAG
    x-google-marketplace:
      type: IMAGE
  alertmanager.image:
    type: string
    default: $REGISTRY/alertmanager:$TAG
    x-google-marketplace:
      type: IMAGE
  kubeStateMetrics.image:
    type: string
    default: $REGISTRY/kubestatemetrics:$TAG
    x-google-marketplace:
      type: IMAGE
  nodeExporter.image:
    type: string
    default: $REGISTRY/nodeexporter:$TAG
    x-google-marketplace:
      type: IMAGE
  grafana.image:
    type: string
    default: $REGISTRY/grafana:$TAG
    x-google-marketplace:
      type: IMAGE
  prometheus.initImage:
    type: string
    default: $REGISTRY/debian9:$TAG
    x-google-marketplace:
      type: IMAGE
  prometheus.serviceAccount:
    type: string
    title: Prometheus Service Account
    description: Service account to assign to main Prometheus StatefulSet
    x-google-marketplace:
      type: SERVICE_ACCOUNT
      serviceAccount:
        roles:
        - type: ClusterRole
          rulesType: PREDEFINED
          rulesFromRoleName: cluster-admin
  kubeStateMetrics.serviceAccount:
    type: string
    title: Kube State Metrics Service Account
    description: Service account to assign to main Kube State Metrics Deployment
    x-google-marketplace:
      type: SERVICE_ACCOUNT
      serviceAccount:
        roles:
        - type: ClusterRole
          rulesType: CUSTOM
          rules:
          - apiGroups: [""]
            resources:
            - configmaps
            - secrets
            - nodes
            - pods
            - services
            - resourcequotas
            - replicationcontrollers
            - limitranges
            - persistentvolumeclaims
            - persistentvolumes
            - namespaces
            - endpoints
            verbs: ["list", "watch"]
          - apiGroups: ["extensions"]
            resources:
            - daemonsets
            - deployments
            - replicasets
            verbs: ["list", "watch"]
          - apiGroups: ["apps"]
            resources:
            - statefulsets
            verbs: ["list", "watch"]
          - apiGroups: ["batch"]
            resources:
            - cronjobs
            - jobs
            verbs: ["list", "watch"]
          - apiGroups: ["autoscaling"]
            resources:
            - horizontalpodautoscalers
            verbs: ["list", "watch"]
  alertmanager.serviceAccount:
    type: string
    title: Alertmanager Service Account
    description: Service account to assign to Alertmanager StatefulSet
    x-google-marketplace:
      type: SERVICE_ACCOUNT
      serviceAccount:
        roles:
        - type: ClusterRole
          rulesType: PREDEFINED
          rulesFromRoleName: cluster-admin
  grafana.serviceAccount:
    type: string
    title: Grafana Service Account
    description: Service account to assign to Grafana StatefulSet
    x-google-marketplace:
      type: SERVICE_ACCOUNT
      serviceAccount:
        roles:
        - type: ClusterRole
          rulesType: PREDEFINED
          rulesFromRoleName: cluster-admin
  nodeExporter.serviceAccount:
    type: string
    title: Node Exporter Service Account
    description: Service account to assign to Node Exporter DaemonSet
    x-google-marketplace:
      type: SERVICE_ACCOUNT
      serviceAccount:
        roles:
        - type: ClusterRole
          rulesType: PREDEFINED
          rulesFromRoleName: cluster-admin
required:
- name
- namespace
- prometheus.replicas
- grafana.password
- alertmanager.image
- kubeStateMetrics.image
- nodeExporter.image
- prometheus.image
- grafana.image
- prometheus.initImage
- prometheus.serviceAccount
- kubeStateMetrics.serviceAccount
- alertmanager.serviceAccount
- grafana.serviceAccount
- nodeExporter.serviceAccount
