matrix:
  include:
  - language: python
    install: pip install jinja2
    script: python -m unittest cloudbuild_k8s_generator_test
  - language: python
    install: pip install jinja2
    script: ./cloudbuild_k8s_generator.py --verify_only
  - language: ruby
    install: gem install foodcritic
    script:
    - foodcritic --version
    - foodcritic --cookbook-path=vm/chef/cookbooks --rule-file=vm/chef/.foodcritic --epic-fai=any
