timeout: 1200s # 20m
options:
  machineType: 'N1_HIGHCPU_8'
steps:

- id: Initialize Git
  name: gcr.io/cloud-builders/git
  entrypoint: bash
  args:
  - -exc
  - |
    # Download Git submodules
    git submodule init
    git submodule sync --recursive
    git submodule update --recursive --init

- id: Get Kubernetes Credentials
  name: gcr.io/cloud-builders/gcloud
  args:
  - container
  - clusters
  - get-credentials
  - '$_CLUSTER_NAME'
  - --region
  - '$_CLUSTER_LOCATION'
  - --project
  - '$PROJECT_ID'

- id: Copy Configurations
  name: gcr.io/google-appengine/debian9
  waitFor:
  - Initialize Git
  - Get Kubernetes Credentials
  env:
  - 'KUBE_CONFIG=/workspace/.kube'
  - 'GCLOUD_CONFIG=/workspace/.config/gcloud'
  # volumes:
  # - name: kube
  #   path: /workspace/.kube
  # - name: gcloud
  #   path: /workspace/.config/gcloud
  entrypoint: bash
  args:
  - -exc
  - |
    ls -al $$HOME/.kube/
    # export KUBE_CONFIG=/workspace/.kube
    mkdir -p $$KUBE_CONFIG
    cp -r $$HOME/.kube/. $$KUBE_CONFIG
    ls -al $$KUBE_CONFIG
    cat $$KUBE_CONFIG/config

    ls -al $$HOME/.config/gcloud
    # export GCLOUD_CONFIG=/workspace/.config/gcloud
    mkdir -p $$GCLOUD_CONFIG
    cp -r $$HOME/.config/gcloud/. $$GCLOUD_CONFIG
    ls -al $$GCLOUD_CONFIG

- id: Verify airflow-operator
  name: gcr.io/cloud-marketplace-tools/k8s/dev:sha_3695cfc
  waitFor:
  - Copy Configurations
  env:
  - 'KUBE_CONFIG=/workspace/.kube'
  - 'GCLOUD_CONFIG=/workspace/.config/gcloud'
  - 'EXTRA_DOCKER_PARAMS=--link metadata:metadata.google.internal'
  # volumes:
  # - name: kube
  #   path: /workspace/.kube
  # - name: gcloud
  #   path: /workspace/.config/gcloud
  dir: k8s/airflow-operator
  args:
  - make
  - '-j4'
  - app/verify

- id: Verify cassandra
  name: gcr.io/cloud-marketplace-tools/k8s/dev:sha_3695cfc
  waitFor:
  - Copy Configurations
  env:
  - 'KUBE_CONFIG=/workspace/.kube'
  - 'GCLOUD_CONFIG=/workspace/.config/gcloud'
  - 'EXTRA_DOCKER_PARAMS=--link metadata:metadata.google.internal'
  # volumes:
  # - name: kube
  #   path: /workspace/.kube
  # - name: gcloud
  #   path: /workspace/.config/gcloud
  dir: k8s/cassandra
  args:
  - make
  - '-j4'
  - app/verify
