timeout: 1200s
options:
  machineType: 'N1_HIGHCPU_8'
steps:

# Initializations

- id: Initialize git
  name: gcr.io/cloud-builders/git
  entrypoint: /bin/bash
  args:
  - -exc
  - |
    # Cloud Build x GitHub integration uses source archives to fetch
    # the source, rather than Git source fetching, and as a consequence
    # does not include the .git/ directory. As a workaround, we clone
    # the repository and reset it to this build's commit sha.
    [[ -e '.git' ]] && exit 0
    git clone 'https://github.com/GoogleCloudPlatform/click-to-deploy.git' tmp
    mv tmp/.git .git
    rm -rf tmp
    git reset "$COMMIT_SHA"
    git submodule sync --recursive
    git submodule update --init --recursive

- id: Get Kubernetes Credentials
  name: gcr.io/cloud-builders/gcloud
  waitFor:
  - '-'
  args:
  - container
  - clusters
  - get-credentials
  - cluster-1
  - --region
  - us-west1-a
  - --project
  - "$PROJECT_ID"

- id: Copy tmpfs Configurations
  name: gcr.io/cloud-builders/gcloud
  waitFor:
  - Get Kubernetes Credentials
  entrypoint: /bin/bash
  args:
  - -exc
  - |
    # Cloud Build mounts the gcloud and kubectl configuration directories
    # as tmpfs volumes, which do not mount via docker --volume. As a
    # workaround, we copy the configuration directories to the workspace
    # and override it.
    cp -r $$HOME/.config/gcloud /workspace
    cp -r $$HOME/.kube /workspace
    mv /workspace/.kube /workspace/kube

- id: Initialized
  name: bash
  waitFor:
  - Initialize git
  - Copy tmpfs Configurations
  - Get Kubernetes Credentials

- id: Verify Airflow Operator
  name: gcr.io/cloud-marketplace-tools/k8s/dev:sha_d1d07a2a02829b7c568cc12e270be371fd0f487f
  waitFor:
  - Initialized
  dir: k8s/airflow-operator
  args:
  - -exc
  - EXTRA_DOCKER_PARAMS="--link metadata:metadata.google.internal" GCLOUD_CONFIG=/workspace/gcloud KUBE_CONFIG=/workspace/kube make -j4 app/verify

- id: Verify Cassandra
  name: gcr.io/cloud-marketplace-tools/k8s/dev:sha_d1d07a2a02829b7c568cc12e270be371fd0f487f
  waitFor:
  - Initialized
  dir: k8s/cassandra
  args:
  - -exc
  - EXTRA_DOCKER_PARAMS="--link metadata:metadata.google.internal" GCLOUD_CONFIG=/workspace/gcloud KUBE_CONFIG=/workspace/kube make -j4 app/verify

- id: Verify Elastic GKE Logging
  name: gcr.io/cloud-marketplace-tools/k8s/dev:sha_d1d07a2a02829b7c568cc12e270be371fd0f487f
  waitFor:
  - Initialized
  dir: k8s/elastic-gke-logging
  args:
  - -exc
  - EXTRA_DOCKER_PARAMS="--link metadata:metadata.google.internal" GCLOUD_CONFIG=/workspace/gcloud KUBE_CONFIG=/workspace/kube make -j4 app/verify

- id: Verify Elasticsearch
  name: gcr.io/cloud-marketplace-tools/k8s/dev:sha_d1d07a2a02829b7c568cc12e270be371fd0f487f
  waitFor:
  - Initialized
  dir: k8s/elasticsearch
  args:
  - -exc
  - EXTRA_DOCKER_PARAMS="--link metadata:metadata.google.internal" GCLOUD_CONFIG=/workspace/gcloud KUBE_CONFIG=/workspace/kube make -j4 app/verify

- id: Verify Grafna
  name: gcr.io/cloud-marketplace-tools/k8s/dev:sha_d1d07a2a02829b7c568cc12e270be371fd0f487f
  waitFor:
  - Initialized
  dir: k8s/grafana
  args:
  - -exc
  - EXTRA_DOCKER_PARAMS="--link metadata:metadata.google.internal" GCLOUD_CONFIG=/workspace/gcloud KUBE_CONFIG=/workspace/kube make -j4 app/verify

- id: Verify Influx DB
  name: gcr.io/cloud-marketplace-tools/k8s/dev:sha_d1d07a2a02829b7c568cc12e270be371fd0f487f
  waitFor:
  - Initialized
  dir: k8s/influxdb
  args:
  - -exc
  - EXTRA_DOCKER_PARAMS="--link metadata:metadata.google.internal" GCLOUD_CONFIG=/workspace/gcloud KUBE_CONFIG=/workspace/kube make -j4 app/verify

- id: Verify Jenkins
  name: gcr.io/cloud-marketplace-tools/k8s/dev:sha_d1d07a2a02829b7c568cc12e270be371fd0f487f
  waitFor:
  - Initialized
  dir: k8s/jenkins
  args:
  - -exc
  - EXTRA_DOCKER_PARAMS="--link metadata:metadata.google.internal" GCLOUD_CONFIG=/workspace/gcloud KUBE_CONFIG=/workspace/kube make -j4 app/verify

- id: Verify Memcached
  name: gcr.io/cloud-marketplace-tools/k8s/dev:sha_d1d07a2a02829b7c568cc12e270be371fd0f487f
  waitFor:
  - Initialized
  dir: k8s/memcached
  args:
  - -exc
  - EXTRA_DOCKER_PARAMS="--link metadata:metadata.google.internal" GCLOUD_CONFIG=/workspace/gcloud KUBE_CONFIG=/workspace/kube make -j4 app/verify

- id: Verify NGINX
  name: gcr.io/cloud-marketplace-tools/k8s/dev:sha_d1d07a2a02829b7c568cc12e270be371fd0f487f
  waitFor:
  - Initialized
  dir: k8s/nginx
  args:
  - -exc
  - EXTRA_DOCKER_PARAMS="--link metadata:metadata.google.internal" GCLOUD_CONFIG=/workspace/gcloud KUBE_CONFIG=/workspace/kube make -j4 app/verify

- id: Verify Prometheus
  name: gcr.io/cloud-marketplace-tools/k8s/dev:sha_d1d07a2a02829b7c568cc12e270be371fd0f487f
  waitFor:
  - Initialized
  dir: k8s/prometheus
  args:
  - -exc
  - EXTRA_DOCKER_PARAMS="--link metadata:metadata.google.internal" GCLOUD_CONFIG=/workspace/gcloud KUBE_CONFIG=/workspace/kube make -j4 app/verify

- id: Verify RabbitMQ
  name: gcr.io/cloud-marketplace-tools/k8s/dev:sha_d1d07a2a02829b7c568cc12e270be371fd0f487f
  waitFor:
  - Initialized
  dir: k8s/rabbitmq
  args:
  - -exc
  - EXTRA_DOCKER_PARAMS="--link metadata:metadata.google.internal" GCLOUD_CONFIG=/workspace/gcloud KUBE_CONFIG=/workspace/kube make -j4 app/verify

- id: Verify Wordpress
  name: gcr.io/cloud-marketplace-tools/k8s/dev:sha_d1d07a2a02829b7c568cc12e270be371fd0f487f
  waitFor:
  - Initialized
  dir: k8s/wordpress
  args:
  - -exc
  - EXTRA_DOCKER_PARAMS="--link metadata:metadata.google.internal" GCLOUD_CONFIG=/workspace/gcloud KUBE_CONFIG=/workspace/kube make -j4 app/verify
