properties:
  APP_INSTANCE_NAME:
    type: string
    x-google-marketplace:
      type: NAME

  NAMESPACE:
    type: string
    x-google-marketplace:
      type: NAMESPACE

  marketplace_installer.service_account:
    type: string
    title: Service account used to bootstrap Agones in the cluster
    x-google-marketplace:
      type: SERVICE_ACCOUNT
      serviceAccount:
        roles:
        - type: ClusterRole
          rulesType: PREDEFINED
          rulesFromRoleName: cluster-admin

  agones.agones.serviceaccount.controller:
    type: string
    title: Service account used by Agones main controller
    x-google-marketplace:
      type: SERVICE_ACCOUNT
      serviceAccount:
        roles:
        - type: ClusterRole
          rulesType: CUSTOM
          rules:
          - apiGroups: ['']
            resources: [events]
            verbs: [create, patch]
          - apiGroups: ['']
            resources: [pods]
            verbs: [create, delete, list, watch]
          - apiGroups: ['']
            resources: [nodes]
            verbs: [list, watch]
          - apiGroups: [apiextensions.k8s.io]
            resources: [customresourcedefinitions]
            verbs: [get]
          - apiGroups: [stable.agones.dev]
            resources: [gameservers, gameserversets]
            verbs: [create, delete, get, list, update, watch]
          - apiGroups: [stable.agones.dev]
            resources: [gameservers]
            verbs: [patch]
          - apiGroups: [stable.agones.dev]
            resources: [fleets, fleetallocations, fleetautoscalers]
            verbs: [get, list, update, watch]
          - apiGroups: [stable.agones.dev]
            resources: [gameserverallocations]
            verbs: [list, watch, delete]

  agones.agones.serviceaccount.sdk:
    type: string
    title: Service account used by Agones sdk controller
    x-google-marketplace:
      type: SERVICE_ACCOUNT
      serviceAccount:
        roles:
        - type: ClusterRole
          rulesType: CUSTOM
          rules:
          - apiGroups: ['']
            resources: [events]
            verbs: [create]
          - apiGroups: [stable.agones.dev]
            resources: [gameservers]
            verbs: [list, update, watch]

  # Images references don't show in the UI and are used to track required
  # binaries for deployment
  marketplace_installer.image:
    type: string
    x-google-marketplace:
      type: DEPLOYER_IMAGE

required:
- APP_INSTANCE_NAME
- NAMESPACE
- marketplace_installer.service_account
- agones.agones.serviceaccount.controller
- agones.agones.serviceaccount.sdk
- marketplace_installer.image
x-google-marketplace:
  publishedVersion: $TAG
  schemaVersion: v2
  applicationApiVersion: v1beta1
  managedUpdates:
    kalmSupported: true
  publishedVersionMetadata:
    releaseTypes:
    - Feature
    recommended: false
    releaseNote: A regular update.
  images:
    ? ''
    : properties:
        AGONES_CONTROLLER_IMAGE:
          type: FULL
    agones-sdk:
      properties:
        AGONES_SDK_IMAGE:
          type: FULL
    agones-ping:
      properties:
        AGONES_PING_IMAGE:
          type: FULL
