application_api_version: v1beta1
properties:
  APP_INSTANCE_NAME:
    type: string
    x-google-marketplace:
      type: NAME
  NAMESPACE:
    type: string
    x-google-marketplace:
      type: NAMESPACE
  IMAGE_JENKINS:
    type: string
    default: $REGISTRY:$TAG
    x-google-marketplace:
      type: IMAGE
  CERTIFICATE_SECRET:
    type: string
    x-google-marketplace:
      type: CERTIFICATE
required:
- APP_INSTANCE_NAME
- NAMESPACE
- IMAGE_JENKINS
- CERTIFICATE_SECRET
