properties:
  name:
    type: string
    x-google-marketplace:
      type: NAME
  namespace:
    type: string
    x-google-marketplace:
      type: NAMESPACE
required:
- name
- namespace
x-google-marketplace:
  managedUpdates:
    kalmSupported: true
  images:
    ? ''
    : properties:
        jenkins.image:
          type: FULL
  publishedVersion: $TAG
  publishedVersionMetadata:
    recommended: false
    releaseTypes:
    - Feature
    releaseNote: A regular update.
  applicationApiVersion: v1beta1
  schemaVersion: v2
