application_api_version: v1beta1
properties:
  APP_INSTANCE_NAME:
    type: string
    x-google-marketplace:
      type: NAME
  NAMESPACE:
    type: string
    x-google-marketplace:
      type: NAMESPACE
  IMAGE_JENKINS:
    type: string
    default: $REGISTRY:$TAG
    x-google-marketplace:
      type: IMAGE
  CERTIFICATE:
    type: string
    x-google-marketplace:
      type: CERTIFICATE
      certificate:
        generatedProperties:
          base64EncodedKey: CERTIFICATE_KEY
          base64EncodedCrt: CERTIFICATE_CRT
required:
- APP_INSTANCE_NAME
- NAMESPACE
- IMAGE_JENKINS
- CERTIFICATE
