x-google-marketplace:
  applicationApiVersion: v1beta1
  # IMPORTANT: These IDs must match your listing ID in Marketplace.
  schemaVersion: v2
  partnerId: click-to-deploy-containers
  solutionId: aditum
  # The release version is required in the schema and MUST match the
  # release tag on the the deployer. Must be in x.x.x format!
  publishedVersion: 1.0.0
  publishedVersionMetadata:
    releaseNote: >-
      First release of Custom Governance.
    # releaseTypes list is optional.
    # "Security" should only be used if this is an important update to patch
    # an existing vulnerability, as such updates will display more prominently for users.
    releaseTypes:
    - Feature
    # If "recommended" is "true", users using older releases are encouraged
    # to update as soon as possible. This is useful if, for example, this release
    # fixes a critical issue.
    recommended: true

  # This MUST be specified to indicate that the deployer supports managed updates.
  # Note that this could be left out or kalmSupported set to false, in
  # which case the deployer uses schema v2 but does not support updates.
  managedUpdates:
    kalmSupported: true
  ## Image Values
  images:
    '':  # Primary image has no name.
      properties:
        aditum.image.repo:
          type: REPO_WITH_REGISTRY
        aditum.image.tag:
          type: TAG
  ## Cluster Constraints
  clusterConstraints:
    gcp:
      nodes:
        requiredOauthScopes:
        - https://www.googleapis.com/auth/cloud-platform
        - https://www.googleapis.com/auth/devstorage.read_only


properties:
  name:
    type: string
    x-google-marketplace:
      type: NAME
  namespace:
    type: string
    x-google-marketplace:
      type: NAMESPACE
  oAuth.clientID:
    type: string
    title: OAuth Client ID
    x-google-marketplace:
      type: STRING
      string:
        generatedProperties:
          base64Encoded: oAuth.clientIDEncoded
  oAuth.clientSecret:
    type: string
    title: OAuth Client Secret
    x-google-marketplace:
      type: STRING
      string:
        generatedProperties:
          base64Encoded: oAuth.clientSecretEncoded
  certificate.hostname:
    type: string
    title: Application Host Address
  deployment.staticIP:
    type: string
    title: Static Address Name
  controller.serviceAccount:
    type: string
    title: Kubernetes Service Account
    x-google-marketplace:
      type: SERVICE_ACCOUNT
      serviceAccount:
        roles:
        - type: ClusterRole
          rulesType: PREDEFINED
          rulesFromRoleName: edit
        - type: ClusterRole
          rulesType: PREDEFINED
          rulesFromRoleName: view
  setupAttributes.initialEmail:
    type: string
    title: Initial User Email
required:
- name
- namespace
- oAuth.clientSecret
- oAuth.clientID
- certificate.hostname
- deployment.staticIP
- setupAttributes.initialEmail
