wordpressImage: null

db:
  image: null
  # TODO(wgrzelak): Fix it!
  exporteImage: prom/mysqld-exporter
  rootPassword: null
  wordpressUser: wordpress
  wordpressPassword: null

admin:
  username: admin
  email: admin@example.com
  password: null

metrics:
  image: null
  enabled: false
