wordpressImage: null

db:
  image: null
  rootPassword: null
  wordpressUser: wordpress
  wordpressPassword: null

  # The image and credentials for mysqld_exporter component.
  # TODO(wgrzelak): This image should not be here.
  exporterImage: prom/mysqld-exporter
  exporterUser: mysqld_exporter
  exporterPassword: null

admin:
  username: admin
  email: admin@example.com
  password: null

metrics:
  image: null
  enabled: false
