properties:
  name:
    type: string
    x-google-marketplace:
      type: NAME
  namespace:
    type: string
    x-google-marketplace:
      type: NAMESPACE
  mariadb.volumeSize:
    type: integer
    title: Volume
    description: The size of Volume (Gi) in the solution
    default: 32
  db.replicas:
    type: integer
    title: Replicas
    description: Number of secondary replicas in MariaDB cluster
    default: 2
    minimum: 1
    maximum: 8
  db.password:
    type: string
    x-google-marketplace:
      type: GENERATED_PASSWORD
      generatedPassword:
        length: 32
  replication.password:
    type: string
    x-google-marketplace:
      type: GENERATED_PASSWORD
      generatedPassword:
        length: 32
required:
- name
- namespace
- db.password
- replication.password
x-google-marketplace:
  managedUpdates:
    kalmSupported: true
  schemaVersion: v2
  publishedVersion: $TAG
  images:
    ? ''
    : properties:
        mariadb.image:
          type: FULL
  publishedVersionMetadata:
    releaseTypes:
    - Feature
    recommended: false
    releaseNote: A regular update.
  applicationApiVersion: v1beta1
