x-google-marketplace:
  schemaVersion: v2

  applicationApiVersion: v1beta1

  publishedVersion: $TAG
  publishedVersionMetadata:
    releaseNote: >-
      Super useful Memcached is it
    releaseTypes:
      - BugFix
    recommended: true

  images:
    memcached:
      properties:
        memcached.image:
          type: FULL
          default: $REGISTRY:$TAG

properties:
  name:
    type: string
    x-google-marketplace:
      type: NAME
  namespace:
    type: string
    x-google-marketplace:
      type: NAMESPACE
  memcached.replicas:
    type: integer
    title: Replicas
    description: The number of Pods in the solution
    default: 3
    minimum: 1
    maximum: 11

required:
- name
- namespace
- memcached.replicas
