properties:
  name:
    type: string
    x-google-marketplace:
      type: NAME
  namespace:
    type: string
    x-google-marketplace:
      type: NAMESPACE
  memcached.replicas:
    type: integer
    title: Replicas
    description: The number of Pods in the solution
    default: 3
    minimum: 1
    maximum: 11
  metrics.enabled:
    type: boolean
    title: Enable Stackdriver Metrics Exporter
    description: Your GCP project should have Stackdriver enabled. For non-GCP clusters,
      export of metrics to Stackdriver is not supported yet
    default: false
required:
- name
- namespace
- memcached.replicas
- metrics.enabled
x-google-marketplace:
  publishedVersionMetadata:
    releaseNote: A regular update.
    recommended: false
    releaseTypes:
    - Feature
  images:
    ? ''
    : properties:
        memcached.image:
          type: FULL
    prometheus-to-sd:
      properties:
        metrics.image:
          type: FULL
  schemaVersion: v2
  managedUpdates:
    kalmSupported: true
  applicationApiVersion: v1beta1
  publishedVersion: $TAG
