properties:
  APP_INSTANCE_NAME:
    type: string
    x-google-marketplace:
      type: NAME
  NAMESPACE:
    type: string
    x-google-marketplace:
      type: NAMESPACE
  SERVICE_ACCOUNT:
    title: Cluster Admin Service Account
    description: >-
      Name of a service account in the target namespace that
      has cluster-admin permissions. This is needed for the operator
      to create Airflow CRD and resources.
    type: string
    x-google-marketplace:
      type: SERVICE_ACCOUNT
      serviceAccount:
        roles:
        - type: ClusterRole
          rulesType: PREDEFINED
          # TODO(barney-s): Reduce the permission set.
          rulesFromRoleName: cluster-admin
required:
- APP_INSTANCE_NAME
- NAMESPACE
- SERVICE_ACCOUNT
x-google-marketplace:
  publishedVersionMetadata:
    recommended: false
    releaseTypes:
    - Feature
    releaseNote: A regular update.
  schemaVersion: v2
  managedUpdates:
    kalmSupported: true
  applicationApiVersion: v1beta1
  images:
    ? ''
    : properties:
        IMAGE_AIRFLOWOPERATOR:
          type: FULL
  publishedVersion: $TAG
