properties:
  name:
    type: string
    x-google-marketplace:
      type: NAME
  namespace:
    type: string
    x-google-marketplace:
      type: NAMESPACE
  elasticsearch.replicas:
    type: integer
    title: Elasticsearch replicas
    description: The number of replicas for Elasticsearch StatefulSet
    default: 2
    minimum: 2
  fluentd.serviceAccount:
    type: string
    title: Fluentd Service Account
    description: Service account to assign to Fluentd StatefulSet
    x-google-marketplace:
      type: SERVICE_ACCOUNT
      serviceAccount:
        roles:
        - type: ClusterRole
          rulesType: CUSTOM
          rules:
          - apiGroups: ['']
            resources: [pods, namespaces]
            verbs: [get, list, watch]
  metrics.enabled:
    type: boolean
    title: Enable Stackdriver Metrics Exporter
    description: Your GCP project should have Stackdriver enabled. For non-GCP clusters,
      export of metrics to Stackdriver is not supported yet
    default: false
required:
- name
- namespace
- elasticsearch.replicas
- fluentd.serviceAccount
- metrics.enabled
x-google-marketplace:
  applicationApiVersion: v1beta1
  managedUpdates:
    kalmSupported: true
  publishedVersionMetadata:
    releaseTypes:
    - Feature
    recommended: false
    releaseNote: A regular update.
  images:
    ? ''
    : properties:
        elasticsearch.image:
          type: FULL
    kibana:
      properties:
        kibana.image:
          type: FULL
    fluentd:
      properties:
        fluentd.image:
          type: FULL
    ubuntu16_04:
      properties:
        initImage:
          type: FULL
    prometheus-to-sd:
      properties:
        metrics.image:
          type: FULL
  publishedVersion: $TAG
  schemaVersion: v2
