apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: web
spec:
  selector:
    matchLabels:
      run: web
  template:
    metadata:
      labels:
        run: web
    spec:
      serviceAccountName: {{ .Values.controller.serviceAccount }}
      containers:
        #TODO: Insert variable for dynamic image URL
      - image: "{{ .Values.aditum.image.repo }}:latest"
        imagePullPolicy: Always
        name: web
        ports:
        - containerPort: 8080
          protocol: TCP
        livenessProbe:
          failureThreshold: 4
          httpGet:
            path: /liveness_check
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 600
          timeoutSeconds: 5
        readinessProbe:
          failureThreshold: 30
          httpGet:
            path: /readiness_check
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 600
          periodSeconds: 5
        env:
        - name: INITIAL_EMAIL
          value: {{ .Values.setupAttributes.initialEmail }}

