properties:
  name:
    type: string
    x-google-marketplace:
      type: NAME
  namespace:
    type: string
    x-google-marketplace:
      type: NAMESPACE
  postgresql.db.password:
    type: string
    x-google-marketplace:
      type: GENERATED_PASSWORD
      generatedPassword:
        length: 12
  metrics.enabled:
    type: boolean
    title: Enable Stackdriver Metrics Exporter
    description: Your GCP project should have Stackdriver enabled. For non-GCP clusters,
      export of metrics to Stackdriver is not supported yet
    default: false

required:
- name
- namespace
- postgresql.db.password
- metrics.enabled
x-google-marketplace:
  publishedVersionMetadata:
    recommended: false
    releaseTypes:
    - Feature
    releaseNote: A regular update.
  schemaVersion: v2
  images:
    ? ''
    : properties:
        sonarqube.image:
          type: FULL
    postgresql-exporter:
      properties:
        postgresql.exporter.image:
          type: FULL
    prometheus-to-sd:
      properties:
        metrics.image:
          type: FULL
    postgresql:
      properties:
        postgresql.image:
          type: FULL
  managedUpdates:
    kalmSupported: true
  publishedVersion: $TAG
  applicationApiVersion: v1beta1
