properties:
  APP_INSTANCE_NAME:
    type: string
    x-google-marketplace:
      type: NAME
  NAMESPACE:
    type: string
    x-google-marketplace:
      type: NAMESPACE
  SAMPLE_APP_PARAMETER1:
    type: integer
    title: Parameter1
    description: Some number
    default: 3
    minimum: 1
    maximum: 6
required:
- APP_INSTANCE_NAME
- NAMESPACE
- SAMPLE_APP_PARAMETER1
x-google-marketplace:
  schemaVersion: v2
  publishedVersionMetadata:
    releaseTypes:
    - Feature
    releaseNote: A regular update.
    recommended: false
  managedUpdates:
    kalmSupported: true
  applicationApiVersion: v1beta1
  images:
    ? ''
    : properties:
        IMAGE_SAMPLE_APP:
          type: FULL
  publishedVersion: $TAG
