x-google-marketplace:
  schemaVersion: v2
  applicationApiVersion: v1beta1
  publishedVersion: '1.7'
  publishedVersionMetadata:
    releaseNote: >-
      Initial release.
    releaseTypes:
    - Feature
    recommended: true
  managedUpdates:
    kalmSupported: true
  images:
    '':
      properties:
        imageInfluxDBRepo:
          type: REPO_WITH_REGISTRY
        imageInfluxDBTag:
          type: TAG    
properties:
  name:
    type: string
    x-google-marketplace:
      type: NAME
  namespace:
    type: string
    x-google-marketplace:
      type: NAMESPACE
  admin.user:
    type: string
    title: InfluxDB admin username
    description: Username for administrator account of InfluxDB database
    default: influxdb-admin
  admin.password:
    type: string
    x-google-marketplace:
      type: GENERATED_PASSWORD
      generatedPassword:
        length: 32
  metrics.image:
    type: string
    default: $REGISTRY/prometheus-to-sd:$TAG
    x-google-marketplace:
      type: IMAGE
  metrics.enabled:
    type: boolean
    title: Enable Stackdriver Metrics Exporter
    description: Your GCP project should have Stackdriver enabled. For non-GCP clusters, export of metrics to Stackdriver is not supported yet
    default: false

required:
- name
- namespace
- admin.user
- admin.password
- metrics.image
- metrics.enabled
