wordpressImage: null

db:
  image: null
  wordpressUser: wordpress
  wordpressPassword: null

enablePublicServiceAndIngress: false

apache:
  exporter:
    image: null

admin:
  username: admin
  email: admin@example.com
  password: null

metrics:
  image: null
  enabled: false

tls:
  base64EncodedPrivateKey: null
  base64EncodedCertificate: null

gcpProjectId: null
