# Copyright 2019 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

_variables:
  from9: &from9 gcr.io/google-appengine/debian9:latest
  nuclio: &nuclio
    version: '1.1.33'
versions:
  - dir: '1/1.1/controller'
    repo: nuclio-controller
    templateSubDir: controller
    tags:
      - '1.1.33-debian9'
      - '1.1-debian9'
      - '1.1.33'
      - '1.1'
      - '1-debian9'
      - '1'
      - 'latest'
    from: *from9
    packages:
      nuclio: *nuclio
  - dir: '1/1.1/dashboard'
    repo: nuclio-dashboard
    templateSubDir: dashboard
    tags:
      - '1.1.33-debian9'
      - '1.1-debian9'
      - '1.1.33'
      - '1.1'
      - '1-debian9'
      - '1'
      - 'latest'
    from: *from9
    packages:
      nuclio: *nuclio
cloudbuild:
  enable_parallel: false
